# Generated by Django 5.0.9 on 2024-12-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, help_text="Describe your reading interests and topics you'd like to see more of", verbose_name='Reading Interests'),
        ),
    ]
