services:
  docs:
    image: news_aggregator_local_docs
    container_name: news_aggregator_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./news_aggregator:/app/news_aggregator:z
    ports:
      - '9000:9000'
    command: /start-docs
