# Generated by Django 5.0.9 on 2024-12-07 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title_translated', models.CharField(blank=True, help_text='AI-translated title', max_length=200, null=True)),
                ('content_translated', models.TextField(blank=True, help_text='AI-translated content', null=True)),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of the content', null=True)),
                ('translation_language', models.CharField(blank=True, help_text='Language code of the translation', max_length=10, null=True)),
                ('last_processed', models.DateTimeField(blank=True, help_text='When the entry was last processed by AI', null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='feed_service.feed')),
            ],
            options={
                'verbose_name_plural': 'Feed entries',
                'ordering': ['-published_at'],
            },
        ),
    ]
