# Generated by Django 5.0.9 on 2024-12-14 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_service', '0005_remove_feedentry_content_translated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedsubscription',
            name='custom_summary',
        ),
        migrations.RemoveField(
            model_name='userfeedsubscription',
            name='relevance_score',
        ),
        migrations.CreateModel(
            name='UserArticleInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_summary', models.TextField(blank=True, default='', help_text='AI-generated summary of the article customized for the user')),
                ('relevance_score', models.IntegerField(default=0, help_text='AI-generated relevance score for the user, from 0 to 100')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='feed_service.feedentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-processed_at'],
                'unique_together': {('user', 'entry')},
            },
        ),
    ]
