# Generated by Django 5.0.9 on 2024-12-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_service', '0006_remove_userfeedsubscription_custom_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedentry',
            name='title_translated',
        ),
        migrations.AddField(
            model_name='userarticleinteraction',
            name='translated_title',
            field=models.CharField(blank=True, default='', help_text='AI-translated or improved title in English', max_length=200),
        ),
    ]
